Repository fairy-taler/frontend, pull requests merged in 2022-10, with the labels that each got.

#19 #2 Feature/member 회원가입 페이지 구현
  package-lock.json
  src/App.js
  src/main/components/common/Navbar.js
  src/member/pages/InputInfo.js
  src/member/pages/Join.js
  src/member/pages/Login.js
  src/member/pages/SelectRole.js
  src/member/static/css/Join.module.css
  src/member/static/images/auth-btn.png
  src/member/static/images/idSearch.png
  src/member/static/images/join-btn.png
  src/member/static/images/join-p.png
  src/member/static/images/join-ph.png
  src/member/static/images/login-btn.png
  src/member/static/images/login-ph.png
  src/member/static/images/logo.png
  src/member/static/images/pwdSearch.png
  src/member/static/images/stud-btn.png
  src/member/static/images/teacher-btn.png
  src/modules/index.js
  src/modules/memberModules/memberModule.js
Labels: :hamster: yuri

#25 Feature/main
  src/App.js
  src/community/pages/NoticeInfo.js
  src/community/pages/NoticeList.js
  src/community/static/css/NoticeInfo.module.css
  src/community/static/css/NoticeList.module.css
  src/main/components/common/Header.js
  src/main/components/common/Navbar.js
Labels: :rabbit: jihee, :no_mouth: simple

#23 #1 헤더 네비게이션 바 css 수정
  src/main/static/css/Header.module.css
  src/main/static/css/Navbar.module.css
Labels: :hamster: yuri, :no_mouth: simple

#26 Feature/10 faq page
  src/community/pages/ServiceCenter.js
  src/community/static/css/ServiceCenter.module.css
  src/community/static/images/inquiry-btn.png
  src/community/static/images/search-btn.png
Labels: :rabbit: jihee, :no_mouth: simple

#36 #34 Add 로그인 시 아이디가 admin이면 리덕스 role을 admin으로 변경
  src/main/components/common/Navbar.js
  src/member/pages/Login.js
  src/modules/index.js
  src/modules/memberModules/loginModule.js
Labels: :rabbit: jihee

#37 Feature/33 manager navbar
  src/main/components/common/Navbar.js
  src/main/static/css/Navbar.module.css
Labels: :hamster: yuri

#45 #39 Add 일대일 문의 답변 페이지
  src/App.js
  src/community/pages/InquiryList.js
  src/community/pages/InquiryResponse.js
Labels: :hamster: yuri

#46 #39 Refactor 답변 완료 된 문의 경우 답변 내용이 보이도록 수정
  src/community/pages/InquiryResponse.js
Labels: :hamster: yuri

#49 Feature/41 management notice list page
  src/App.js
  src/community/pages/NoticeInfoForManagement.js
  src/community/pages/NoticeListForManagement.js
  src/community/static/css/NoticeInfoForManagement.module.css
  src/community/static/css/NoticeListForManagement.module.css
  src/main/components/common/Navbar.js
Labels: :rabbit: jihee

#56 #53 Add 커뮤니티 게시판 전체 조회 페이지 구현
  src/App.js
  src/community/pages/Forums.js
  src/community/static/css/Forums.module.css
  src/main/components/common/Navbar.js
Labels: :hamster: yuri
